# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Assert images exist
          command: $LANDING=./public/imgs/landingImage.jpg
            if test -f "$LANDING"; then
            echo "$LANDING exists";
            else
            echo "$LANDING does not exist"
            exit 1
            fi

      - run: npm install

      - run: npm test

  deploy:
    docker:
      - image: circleci/node:10.15.1

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - run: npm test

      - run: npm run build

      - run: npm install firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"

workflows:
  version: 2

  buildTest:
    jobs:
      - build # also runs the tests

  buildTestDeploy:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy # also runs build and test
