# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources

  build:
    docker:
      - image: circleci/node:10.15.1

    working_directory: ~/repo

    steps:
      - checkout

      - run: |
          echo Checking for images
          set -o nounset
          set -o errexit
          set -o pipefail
          $LANDING=./public/imgs/landingImage.jpg
          [[ -f $LANDING ]] && echo "$LANDING exists" || (echo "$LANDING does not exist" && exit 1)

      - run: npm install

      - run: npm test

  deploy:
    docker:
      - image: circleci/node:10.15.1

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - run: npm test

      - run: npm run build

      - run: npm install firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"

workflows:
  version: 2

  buildTest:
    jobs:
      #- shellcheck
      - build # also runs the tests
        # requires:
        #   - shellcheck

  buildTestDeploy:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      #- shellcheck
      - deploy # also runs build and test
